services:
  keycloak:
    container_name: pev_kc
    image: quay.io/keycloak/keycloak:26.3
    command: start-dev --import-realm
    environment:
      DEBUG: 'true'
      DEBUG_PORT: '*:8787'
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_SPI_EVENTS_LISTENER_JBOSS_LOGGING_SUCCESS_LEVEL: info
      KC_LOG_LEVEL: INFO,de.keycloak:debug
    ports:
      - "8080:8080"
      - "8787:8787"
    volumes:
      - kc_data:/opt/keycloak/data
      - ./src/test/resources/test-realm.json:/opt/keycloak/data/import/test-realm.json
      - ./target/periodic-email-verification.jar:/opt/keycloak/providers/periodic-email-verification.jar
  mail:
    # UI: http://localhost:8025
    container_name: pev_mail
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"

volumes:
  kc_data:
    name: pev-kc-data
